name: diff-wos
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - numpy=1.24.3
  - pytest=7.4.0
  - python=3.11.5
  - pybind11=2.11.1
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip
  - pip:
      - drjit==0.4.4
      - imageio==2.31.4
      - ipywidgets==8.1.1
      - jupyterlab-widgets==3.0.9
      - matplotlib==3.7.3
      - mitsuba==3.5.0
      - scikit-image==0.21.0
      - scipy==1.10.1
      - tensorboard==2.17.0